### ISSUE TITLE
Undefined variable: KOKEN_DATABASE

### ISSUE THREAD

**Issue by repiuk** [sylvaindeloux/koken-cache-warmup#1]
Hi

I get this error if I run the script (from osx terminal)

PHP Notice: Undefined variable: KOKEN_DATABASE in /Library/Server/Web/Data/Sites/koken/cache-warmup.php on line 45

**Comment by sylvaindeloux** [comment]
Hi,

I think there is an issue in your database config file (maybe a different var name, from a previous version of Koken?).
Is there any other error message?
Can you show me the content of the /storage/configuration/database.php ? DON’T FORGET TO REMOVE THE CONFIDENTIAL DATA FROM THE FILE before pasting it here ;)

**Comment by repiuk** [comment]
Before the line
require($databaseConfigFile);

I have placed this code (which is was I "copied" form database.php). I don't know how to fill the array from a file.

$KOKEN_DATABASE = Array(
      'driver' => 'mysqli',
      'hostname' => 'localhost',
      'database' => 'Koken',
      'username' => 'your_database_account',
      'password' => 'your_database_password',
      'prefix' => 'koken_',
      'socket' => ''
   );

And now it runs

**Comment by sylvaindeloux** [comment]
The initial purpose of my script was to load these credentials from Koken config file. I think there is an issue with the loading of the db file.

Which version of Koken do you use?

**Comment by repiuk** [comment]
0.21.2
database.php content
<?php
	return array(
		'driver' => 'mysqli',
		'hostname' => 'localhost',
		'database' => 'Koken',
		'username' => '****',
		'password' => '****',
		'prefix' => 'koken_',
		'socket' => ''
	);

**Comment by sylvaindeloux** [comment]
Thanks for your feedback.
That’s weird, I use the same version (0.21.2, the latest) and my database.php is not the same. I’ll check the internal code of Koken tounderstant why they did that and update my script.

**Comment by BlackSkorpio** [comment]
Hi @sylvaindeloux Did get any leads in this issue?
Btw: hope everything is ok with you :)

**Comment by georg90** [comment]
You can just use this on line 42:
```$KOKEN_DATABASE = require($databaseConfigFile);```
